# Generated by Django 5.0.6 on 2024-06-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_Id', models.IntegerField(auto_created=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('preco', models.IntegerField()),
                ('mtd_pg', models.TextField(max_length=100)),
            ],
        ),
    ]
